#import "@preview/bookly:3.1.0": *

#let abs = [
  Software Defined Networking (SDN) is a paradigm shift in network architecture
  that separates the control plane---the logic that determines how traffic
  should be forwarded---from the data plane---the physical infrastructure that
  implements that forwarding. Where traditional networks embed control
  intelligence in each individual device, producing a decentralized system that
  is difficult to reason about globally and slow to adapt to changing
  conditions, SDN centralizes control in a logically unified software controller
  and reduces network devices to fast, programmable packet forwarders governed
  by flow rules the controller installs. This chapter traces the motivation for
  this transition through the evolving demands of modern traffic patterns,
  examines the SDN architectural framework---data plane, controller, northbound
  and southbound APIs, and control applications---and analyzes the match-action
  forwarding abstraction and its concrete realization in OpenFlow. The
  mechanisms by which a controller discovers network topology and computes
  forwarding paths are described in detail. Two applications close the chapter:
  Google's B4 wide-area network, which demonstrates how SDN enables near-100%
  WAN link utilization through centralized traffic engineering, and the P4
  language, which extends programmability from the control plane into the data
  plane itself. The recurring tension is between the distributed,
  failure-resilient design of the traditional Internet and the performance and
  flexibility benefits of logical centralization.
]

#chapter(
  title: "Software Defined Networking",
  abstract: abs,
  toc: true,
)[

  == Motivations: The Limits of Traditional Network Control

  === From Volume to Variability

  The argument for SDN begins not with a technical claim but with an empirical
  observation about how traffic patterns have changed. The fundamental design
  assumption of the traditional Internet---that traffic flows from clients to
  servers along relatively stable paths, and that routing protocols can compute
  these paths independently on each router---was reasonable when the dominant
  application was a user retrieving a web page from a single server. It
  describes poorly the traffic generated by modern distributed applications,
  cloud services, mobile devices, and real-time unified communications
  platforms.

  Modern distributed applications interact with multiple backend services
  simultaneously, generating substantial _horizontal_ (server-to-server) traffic
  alongside the traditional vertical (client-to-server) traffic. Unified
  Communications platforms integrate voice, video, messaging, and presence into
  a single service, each component with distinct QoS requirements for latency,
  jitter, and loss. Cloud computing has relocated traffic that was previously
  contained within enterprise networks onto wide-area links, whose load is now
  unpredictable and application-dependent. Server virtualization allows virtual
  machines to migrate between physical hosts, causing traffic patterns to shift
  in ways that the network cannot anticipate. Mobile devices create rapidly
  changing attachment points and generate bursty, heterogeneous loads. By some
  estimates, over 70 percent of modern data center traffic is now
  East-West---between servers within the same facility---rather than North-South
  between clients and servers, yet traditional three-tier data center
  architectures (Access, Aggregation, Core) were designed and optimized for
  North-South flows.

  The consequence is that traffic has become time-variant, spatially dynamic,
  and application-sensitive. A routing system that can only set link weights and
  compute shortest paths based on those weights---the only "control knobs"
  available in traditional routing---is structurally unable to express the
  fine-grained, policy-driven forwarding decisions that modern applications
  require.

  === The Architectural Absence of Abstraction

  The Internet's success as a data delivery infrastructure rests on a clean
  layered architecture in which each layer provides a well-defined service
  abstraction to the layer above, hides internal complexity, and enables
  independent innovation. This principle---which allowed TCP to be designed
  independently of IP, and IP independently of Ethernet---is one of the most
  powerful ideas in systems engineering.

  The control and management plane of traditional networks, however, was built
  with no analogous architectural abstraction. Rather than defining a clean
  interface between "what the network should do" and "how it should do it,"
  every new network requirement produced a new protocol: spanning tree to
  prevent loops, OSPF and BGP for routing, ACLs for access control, RSVP for
  resource reservation, MPLS for traffic engineering. Each protocol was designed
  independently, interfaces between them are complex and fragile, and the
  resulting system is a collection of interacting mechanisms rather than a
  coherent architecture. Network devices are closed, proprietary boxes that
  bundle control logic with forwarding hardware; vendor-specific interfaces make
  programming or extending this logic extremely difficult; and the slow pace of
  standards development means that innovation requires years from conception to
  deployment.

  Three specific limitations characterize this situation. First, the
  architecture is _static and complex_: independently designed protocols each
  solve a narrow problem, and their interactions produce fragmented,
  hard-to-manage behavior. Second, it suffers from _policy inconsistency and
  operational rigidity_: configuration changes must be applied manually across
  dozens or hundreds of devices, policies are enforced locally without global
  coordination, and misconfiguration is a leading cause of network outages.
  Third, it exhibits _vendor dependence and limited innovation_: control logic
  embedded in proprietary hardware cannot be changed without vendor cooperation,
  open programmability interfaces do not exist, and the deployment of new
  services is slow.

  == SDN: Core Concepts

  === Separating Control and Data Planes

  Every network device performs two logically distinct functions at the network
  layer. _Forwarding_ (the data plane) moves individual packets from an input
  port to the appropriate output port based on a forwarding table, and operates
  at packet timescales---nanoseconds to microseconds. _Routing_ (the control
  plane) determines how forwarding tables should be populated by computing paths
  through the network, and operates at much slower control timescales---seconds
  to minutes, triggered by topology changes or policy updates.

  In traditional IP networks, these two functions are tightly coupled within
  each device: every router runs its own routing protocol, computes its own
  forwarding table, and forwards packets independently. Control intelligence is
  distributed across all devices, and global behavior emerges from the
  interaction of many independent local decisions. This distribution was a
  deliberate design choice in the early Internet, motivated by the goal of
  resilience: a network with no centralized points of failure can survive the
  loss of any individual node.

  SDN's central idea is to separate these planes, implementing the data plane in
  simple, fast forwarding hardware while relocating control logic to a
  _logically centralized_ software controller external to the forwarding
  devices. The controller maintains a global view of network state and computes
  forwarding tables for all devices, which are installed in those devices
  through a standardized interface. The forwarding devices themselves need not
  run any routing protocol or make any autonomous forwarding decisions; they
  simply execute rules the controller provides.

  The distinction between _logically_ and _physically_ centralized is important.
  A logically centralized controller presents a single, coherent view of the
  network to applications built on top of it, but can be implemented as a
  distributed system of multiple physical servers for performance, fault
  tolerance, and scalability. Logical centralization gives the benefits of a
  global network view without requiring a single physical point of failure.

  === Why Logical Centralization Helps

  In the distributed control model, each router independently computes
  forwarding tables as a function of local topology and link-weight
  configuration: $T_i = "SPF"("Topology", "link weights")$. The resulting
  forwarding behavior is determined entirely by the topology and link weights,
  with no mechanism to incorporate traffic demand, application-level policies,
  or global optimization objectives. There is no single entity that can
  simultaneously observe all traffic flows and coordinate their routing.

  A logically centralized controller computes
  $cal(F): S(t) -> {T_1, T_2, ..., T_n}$, where $S(t)$ is the global network
  state at time $t$---topology, traffic demand, and operator policies---and
  $T_i$ is the forwarding table for device $i$. This formulation makes explicit
  what traditional routing cannot express: forwarding tables are computed
  consistently across the network from a unified state that incorporates demand
  and policy, not just topology. Any routing desired by the
  operator---path-specific, flow-specific, load-balanced across multiple paths,
  application-differentiated---can in principle be expressed and enforced.

  == The SDN Data Plane and Match-Action Forwarding

  === Generalized Forwarding

  Traditional destination-based forwarding makes a single decision: given the
  destination IP address of an arriving packet, find the longest-prefix match in
  the forwarding table and send the packet out the corresponding port. This
  decision is based on one field of one header. SDN's data plane abstracts this
  into a _generalized_ match-action model: examine any combination of fields
  across the link, network, and transport layer headers, match against a set of
  rules, and execute any of a rich set of actions.

  A _flow table_ (also called a forwarding table in the SDN context) is the
  primary data structure in an SDN-capable device. Each entry in the flow table
  specifies a _match_ pattern (values or wildcards for header fields such as
  ingress port, source and destination MAC addresses, VLAN tag, source and
  destination IP addresses, IP protocol, ToS byte, TCP/UDP source and
  destination ports), an _action_ to execute on matching packets (forward to one
  or more output ports, drop, modify header fields, encapsulate and send to the
  controller), a _priority_ for disambiguating overlapping patterns, and
  _counters_ that track packet and byte counts for monitoring.

  This abstraction unifies the forwarding semantics of several distinct device
  types. A router performs longest-prefix-match on the destination IP address
  and forwards to a port---expressible as a flow table rule matching on IP
  destination with a forward action. A firewall matches on source or destination
  address and port number and either permits or denies---expressible as flow
  table rules with drop actions. A NAT device matches on IP address and port and
  rewrites them---expressible as flow table rules with field-modification
  actions. A load balancer selects among multiple destination
  addresses---expressible using group table entries. The match-action
  abstraction is thus not merely a routing mechanism but a general-purpose
  packet processing primitive.

  === OpenFlow

  OpenFlow is the most widely deployed concrete realization of the SDN
  southbound API---the interface between the controller and the forwarding
  devices. Introduced by McKeown et al. at Stanford in 2008 and subsequently
  standardized by the Open Networking Foundation, OpenFlow defines both the flow
  table structure and the protocol by which a controller installs, modifies, and
  deletes flow entries in OpenFlow-capable switches. OpenFlow uses TCP as its
  transport (with optional TLS encryption for security) and defines three
  classes of messages: controller-to-switch messages (including FEATURES to
  query switch capabilities, MODIFY-STATE to add or delete flow entries, and
  PACKET-OUT to inject packets into the switch), switch-to-controller messages
  (including PACKET-IN to forward an unmatched packet to the controller,
  FLOW-REMOVED to notify the controller when a flow entry expires, and
  PORT-STATUS to report link status changes), and symmetric messages for
  connection management.

  A concrete example clarifies the power of the model. A flow entry with match
  pattern `IP Dst = 51.6.0.8` and action `forward(port 6)` implements
  destination-based routing. An entry with match `TCP dst-port = 22` and action
  `drop` blocks SSH traffic---a firewall rule. An entry with match
  `IP Src = 128.119.1.1` and action `drop` blocks all traffic from a specific
  host. These rules coexist in the same flow table with different priorities,
  and the first matching rule (by priority order) determines how each packet is
  handled.

  === The Flow Table Pipeline

  A switch may contain a single flow table or a pipeline of multiple flow
  tables, numbered from 0 upward. A packet is first matched against table 0; a
  matching entry may include a GoTo instruction directing the packet to a later
  table in the pipeline, where further matching and action execution occurs.
  This multi-table pipeline provides considerable flexibility: early tables may
  classify traffic by protocol or QoS class, while later tables may apply
  class-specific forwarding decisions. The pipeline structure also allows the
  controller to implement complex processing logic---analogous to a series of
  if-then-else steps in a program---without requiring each step to be encoded in
  a single flat table.

  When a packet matches multiple entries in a table, the highest-priority entry
  wins. If no entry matches and no table-miss entry has been configured, the
  packet is dropped. If a table-miss entry exists, it specifies one of three
  behaviors: send the packet to the controller (allowing reactive rule
  installation), direct the packet to the next table in the pipeline, or drop
  it.

  _Group tables_ extend the pipeline with multicast and load-balancing
  capabilities. A flow entry may direct matching packets to a group entry rather
  than a single output port. Group entries come in several types: All (send to
  all buckets, used for broadcast or multicast), Select (send to a single bucket
  chosen by a load-balancing algorithm), Fast Failover (send to the first live
  bucket), and Indirect (send to a single designated bucket). Group tables allow
  a single flow rule to express fan-out, load balancing, and failover behaviors
  that would otherwise require multiple flow entries.

  == The SDN Control Plane

  === Controller Architecture

  The SDN controller, sometimes called the Network Operating System (NOS),
  provides a network-wide abstraction layer between the raw state of the
  forwarding devices and the control applications that implement network
  behavior. It is organized into three functional layers. The _communication
  layer_ handles the protocols by which the controller interacts with forwarding
  devices, primarily OpenFlow but also SNMP and NETCONF for device management.
  The _network-wide state management layer_ maintains a distributed database of
  network state: topology (links and their status), flow statistics, host
  locations, and switch configurations. This database is the "single source of
  truth" that control applications query. The _interface layer_ exposes network
  state to control applications through a northbound API---typically RESTful
  HTTP interfaces or intent-based abstractions---allowing applications to query
  the topology, install flow rules, and subscribe to state change notifications.

  Two major open-source SDN controllers illustrate different architectural
  philosophies. OpenDaylight (ODL) is organized around a Service Abstraction
  Layer (SAL) that decouples internal services (topology processing, forwarding
  rule management, host tracking, statistics collection) from both the
  southbound protocols and the northbound application interfaces. ODL exposes
  its northbound API through REST, RESTCONF, and NETCONF, supporting a wide
  range of management clients. ONOS (Open Network Operating System), developed
  with strong emphasis on large-scale deployment, emphasizes a distributed core
  with explicit consistency and replication mechanisms, an intent framework that
  allows applications to specify network behavior at a high level (what the
  network should do, not how), and separation of control applications from the
  controller core.

  === Topology Discovery with LLDP

  Before the controller can compute any forwarding paths, it must build a model
  of the physical network topology---which switches exist, which ports they
  have, and which ports are connected to which other ports or to hosts. This is
  the _topology discovery_ problem.

  At initialization, each OpenFlow switch establishes a TCP connection to the
  controller and completes a feature handshake: the controller sends a FEATURES
  REQUEST message, and the switch replies with its Switch ID and a list of
  active ports. After this handshake, the controller knows every switch and its
  ports but does not yet know which ports are physically connected to which
  other switches.

  Topology discovery uses the _Link Layer Discovery Protocol_ (LLDP), a
  vendor-neutral IEEE standard operating at Layer 2. In OpenFlow networks, every
  switch has a pre-installed flow rule that forwards all LLDP frames to the
  controller via a PACKET-IN message. To discover the link between two switches,
  the controller generates a PACKET-OUT message for each active port of each
  switch, encapsulating an LLDP frame whose payload identifies the originating
  switch and port. When this LLDP frame reaches an adjacent switch (over the
  physical link connecting the two), the pre-installed LLDP rule triggers a
  PACKET-IN message back to the controller, carrying the switch ID and port
  where the frame was received. The controller extracts the originating
  switch/port from the LLDP payload and the receiving switch/port from the
  PACKET-IN metadata, and records the link: (srcSwitch, srcPort) --- (dstSwitch,
  dstPort). Repeating this process for all ports of all switches reveals the
  complete inter-switch topology. For a network of $S$ switches with a total of
  $P$ active ports across all switches, the discovery requires exactly $P$
  PACKET-OUT messages.

  Host reachability is discovered reactively. When a host sends its first packet
  into the network and the ingress switch has no matching flow entry, the switch
  sends a PACKET-IN to the controller. The controller records the association
  between the host's MAC address and the (switch, port) where it was observed,
  updating the host table. Future flow rules can then route traffic to this host
  based on this table entry.

  === Routing in SDN

  With the topology known, the controller can run any routing
  algorithm---Dijkstra's shortest-path, load-balanced multipath,
  application-aware policy routing---on the full network graph. When the
  topology changes (a link fails, triggering a PORT-STATUS message from the
  affected switch), the routing application is notified through a registered
  callback, recomputes affected paths, and issues MODIFY-STATE messages to
  update flow entries in the relevant switches. This sequence illustrates the
  event-driven programming model of SDN: network state changes propagate from
  the data plane through the southbound API to the controller's state database,
  trigger registered application callbacks, and result in flow rule updates
  pushed back to the data plane.

  Path computation results in FlowMod messages sent to each switch along the
  computed path. To avoid transient routing loops during installation, these
  messages are sent in reverse order---from the switch closest to the
  destination backward to the source switch. All future packets from the same
  flow will match the newly installed rules directly at each switch without
  requiring a trip to the controller.

  == Applications of SDN

  === B4: Google's Software-Defined WAN

  Google's B4 network, first described at ACM SIGCOMM 2013, is among the most
  significant real-world deployments of SDN and demonstrates the technology's
  value at scale. B4 is Google's private WAN interconnecting its global data
  centers---not the public-facing backbone, but the internal backbone over which
  the company replicates data, synchronizes state, and runs distributed
  computations across geographically distributed infrastructure.

  The motivation for B4 was economic. Traditional WAN links are expensive, and
  traditional routing protocols treat all traffic equally, provisioning for peak
  demand and achieving typical utilization of only 30-40% before congestion
  occurs. The overprovisioning factor of 2-3× required to maintain acceptable
  performance was unsustainable given Google's rapid WAN traffic growth. B4's
  goal was to achieve near-100% utilization on expensive long-haul links while
  still meeting the QoS requirements of different traffic classes.

  B4 distinguishes three traffic flow types with different priority and latency
  sensitivity. User data replication---the lowest volume but most
  latency-sensitive traffic---has highest priority. Remote storage access for
  geographically distributed computation is moderately sensitive to latency and
  has moderate priority. Large-scale data synchronization across data
  centers---the highest volume but least latency-sensitive traffic---has lowest
  priority. The key insight is that the lowest-priority class can tolerate
  reduced bandwidth during periods of congestion and can be shed first when link
  capacity is insufficient.

  B4's architecture has three layers. The _switch layer_ uses low-cost commodity
  silicon switches with no complex control software---purely forwarding devices.
  The _control layer_ runs OpenFlow controllers (OFCs) on Network Control
  Servers (NCS) at each site, maintaining network state and translating
  instructions from the global layer into OpenFlow rules installed in switches.
  For fault tolerance, a Paxos consensus protocol elects a primary controller
  instance from several replicas at each site. The _global layer_ runs an SDN
  Gateway that abstracts switch hardware details, and a central Traffic
  Engineering (TE) server that computes site-level path and bandwidth
  assignments.

  The TE server operates on a simplified topology in which each B4 site is a
  vertex and inter-site links are edges, abstracting away the internal structure
  of each site. Traffic demands are expressed as _flow groups_---tuples of
  (source site, destination site, QoS class)---rather than individual
  application flows, since the TE algorithm cannot operate at per-flow
  granularity. The TE server outputs _tunnels_ (site-level paths expressed as
  sequences of sites, implemented using IP-in-IP encapsulation) and _tunnel
  groups_ (mappings from flow groups to tunnels with bandwidth allocations).
  These assignments are forwarded to the OFCs via the SDN Gateway, which install
  them in switches as OpenFlow rules. Load balancing across multiple tunnels for
  the same flow group is achieved by hashing packet header fields modulo the
  number of tunnel entries.

  The results were striking. B4 achieved near-100% utilization on its WAN links
  for elastic traffic, compared to the 30-40% typical of traditional WAN
  deployments---a 2-3× improvement in effective capacity from the same physical
  infrastructure, without deploying any new links. The centralized TE server
  enabled global optimization that no distributed routing protocol could match.

  === Service Function Chaining

  A second major SDN application is _Service Function Chaining_ (SFC): the
  dynamic definition and enforcement of ordered sequences of network functions
  (firewall, intrusion detection, load balancer, DDoS protection, NAT) through
  which specific traffic flows must pass. In a traditional network, service
  chains are encoded in the physical topology; changing the chain requires
  reconfiguring routing. With SDN, the controller can steer any traffic flow
  through any sequence of network functions by installing appropriate flow rules
  at each switch along the path, without physical network changes. A
  subscriber's web traffic might traverse a firewall and a cache; an enterprise
  application might additionally traverse an IDS and a load balancer; traffic
  from a guest VLAN might be redirected to a captive portal. All of these chains
  can coexist and be dynamically reconfigured by the controller.

  == Towards a Programmable Data Plane: P4

  === Limitations of OpenFlow

  OpenFlow has been enormously influential, but it has a fundamental limitation:
  it defines a fixed set of header fields that can be matched and a fixed set of
  actions that can be taken, determined by the OpenFlow specification itself.
  The specification began with approximately 12 header fields and grew to around
  40 as use cases expanded---but any field or action not in the specification
  cannot be used, regardless of what the underlying hardware might be capable
  of. New forms of packet encapsulation (VXLAN, NVGRE, segment routing headers)
  require specification updates and hardware redesign cycles, reintroducing the
  slow innovation cycle that SDN was meant to eliminate.

  True network programmability requires the ability to specify not only which
  rules to install in existing tables (control plane programmability) but also
  which tables exist and how they process packets (data plane programmability).
  OpenFlow provides the former but not the latter.

  === P4: Programming Protocol-Independent Packet Processors

  P4, introduced in a landmark ACM SIGCOMM 2014 paper and now standardized by
  the P4 Language Consortium, is a domain-specific language for programming the
  data plane of network devices. A P4 program completely describes the packet
  processing pipeline that a target device should implement: which header fields
  exist and how they are structured, how an incoming packet is parsed to extract
  those fields, which tables are available for matching, what actions each table
  can execute, and how execution flows among tables.

  A P4 program is compiled by a vendor-supplied compiler to two artifacts: a
  _data plane configuration_ that implements the forwarding logic on the target
  hardware (a P4-capable switch, SmartNIC, or software switch), and a _control
  plane API_ (using the P4Runtime specification) through which the controller
  populates flow tables at runtime. The separation between the compiled data
  plane configuration (which defines the pipeline's structure) and the runtime
  API (which populates its tables) mirrors the separation between a program and
  its data---the same pipeline structure can be instantiated with different
  rules for different deployments.

  The key P4 abstractions are headers, parsers, tables, and control flow.
  _Header definitions_ specify the format and field widths of packet
  headers---Ethernet, IPv4, custom protocols---in a strongly typed manner. The
  _parser_ is a state machine that extracts header fields from the raw packet
  byte stream; it begins in a start state, extracts the Ethernet header, and
  transitions based on the EtherType field (for example, to a parse_ipv4 state
  if EtherType is 0x0800). _Tables_ specify the match fields, possible actions,
  and default behavior for a stage of the pipeline; the control plane populates
  them with specific rules at runtime. The _control_ block specifies how tables
  are applied in sequence, including conditional logic.

  P4 enables network operators to define entirely custom protocols and
  processing behaviors without involving equipment vendors. A network operator
  can add a new monitoring header, implement a custom load-balancing algorithm,
  or deploy a novel congestion control mechanism by writing a P4 program,
  compiling it for their target hardware, and deploying it---without waiting for
  a standards update or a new hardware release. This represents the full
  realization of the programmable network vision: both the control plane (what
  rules are installed) and the data plane (how packets are processed) are under
  operator control.

  == Open Challenges

  SDN's architectural clarity does not eliminate all problems; it transforms
  them. The controller, though logically centralized, must be implemented as a
  distributed system to achieve acceptable performance and fault tolerance---and
  distributed system correctness (consistency, availability under failures) is
  itself a hard problem. The southbound API between controller and switches
  introduces a communication bottleneck: when a previously unseen flow arrives
  at a switch and triggers a PACKET-IN, the latency of the round-trip to the
  controller determines how long the first packets of that flow are delayed or
  dropped. Reactive rule installation is therefore unsuitable for
  latency-sensitive flows; proactive rule installation (pre-populating rules
  before flows arrive) requires accurate traffic prediction.

  Security is a significant concern: a compromised controller has full authority
  over all network behavior, making it a high-value target. The northbound API,
  through which third-party applications install flow rules, must enforce
  authorization to prevent untrusted applications from subverting network
  policy. And the transition from traditional networks to SDN-capable
  infrastructure cannot happen instantaneously; hybrid deployments---where some
  devices support OpenFlow and others do not---introduce integration challenges
  that the clean SDN architecture does not address.

  These challenges notwithstanding, the trajectory of the field is clear. SDN is
  no longer a research curiosity: it underlies the virtual networking
  infrastructure of every major cloud provider, the WAN management systems of
  global internet companies, and the control planes of 5G core networks. The
  combination of SDN for control plane flexibility and P4 for data plane
  programmability is establishing the foundation for a genuinely programmable
  network infrastructure.

]
